package org.example.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.mybatis.pojo.AclPermissionEmp;
import org.example.mybatis.pojo.AclPermissionEmpExample;

public interface AclPermissionEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int countByExample(AclPermissionEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int deleteByExample(AclPermissionEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int insert(AclPermissionEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int insertSelective(AclPermissionEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    List<AclPermissionEmp> selectByExample(AclPermissionEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    AclPermissionEmp selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByExampleSelective(@Param("record") AclPermissionEmp record, @Param("example") AclPermissionEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByExample(@Param("record") AclPermissionEmp record, @Param("example") AclPermissionEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByPrimaryKeySelective(AclPermissionEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByPrimaryKey(AclPermissionEmp record);
}