package org.example.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.mybatis.pojo.AclRolePermissionEmp;
import org.example.mybatis.pojo.AclRolePermissionEmpExample;

public interface AclRolePermissionEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int countByExample(AclRolePermissionEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int deleteByExample(AclRolePermissionEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int insert(AclRolePermissionEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int insertSelective(AclRolePermissionEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    List<AclRolePermissionEmp> selectByExample(AclRolePermissionEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    AclRolePermissionEmp selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByExampleSelective(@Param("record") AclRolePermissionEmp record, @Param("example") AclRolePermissionEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByExample(@Param("record") AclRolePermissionEmp record, @Param("example") AclRolePermissionEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByPrimaryKeySelective(AclRolePermissionEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role_permission
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByPrimaryKey(AclRolePermissionEmp record);
}