package org.example.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.mybatis.pojo.AclRoleEmp;
import org.example.mybatis.pojo.AclRoleEmpExample;

public interface AclRoleEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int countByExample(AclRoleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int deleteByExample(AclRoleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int insert(AclRoleEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int insertSelective(AclRoleEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    List<AclRoleEmp> selectByExample(AclRoleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    AclRoleEmp selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByExampleSelective(@Param("record") AclRoleEmp record, @Param("example") AclRoleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByExample(@Param("record") AclRoleEmp record, @Param("example") AclRoleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByPrimaryKeySelective(AclRoleEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByPrimaryKey(AclRoleEmp record);
}