package org.example.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.mybatis.pojo.AclUserRoleEmp;
import org.example.mybatis.pojo.AclUserRoleEmpExample;

public interface AclUserRoleEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int countByExample(AclUserRoleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int deleteByExample(AclUserRoleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int insert(AclUserRoleEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int insertSelective(AclUserRoleEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    List<AclUserRoleEmp> selectByExample(AclUserRoleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    AclUserRoleEmp selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByExampleSelective(@Param("record") AclUserRoleEmp record, @Param("example") AclUserRoleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByExample(@Param("record") AclUserRoleEmp record, @Param("example") AclUserRoleEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByPrimaryKeySelective(AclUserRoleEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user_role
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByPrimaryKey(AclUserRoleEmp record);
}