package org.example.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.mybatis.pojo.AclUserEmp;
import org.example.mybatis.pojo.AclUserEmpExample;

public interface AclUserEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int countByExample(AclUserEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int deleteByExample(AclUserEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int insert(AclUserEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int insertSelective(AclUserEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    List<AclUserEmp> selectByExample(AclUserEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    AclUserEmp selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByExampleSelective(@Param("record") AclUserEmp record, @Param("example") AclUserEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByExample(@Param("record") AclUserEmp record, @Param("example") AclUserEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByPrimaryKeySelective(AclUserEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_user
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    int updateByPrimaryKey(AclUserEmp record);
}