package org.example.mybatis.pojo;

import java.util.Date;

public class AclRoleEmp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_role.id
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_role.role_name
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_role.role_code
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_role.remark
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_role.is_deleted
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_role.gmt_create
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_role.gmt_modified
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_role.id
     *
     * @return the value of acl_role.id
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_role.id
     *
     * @param id the value for acl_role.id
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_role.role_name
     *
     * @return the value of acl_role.role_name
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_role.role_name
     *
     * @param roleName the value for acl_role.role_name
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_role.role_code
     *
     * @return the value of acl_role.role_code
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_role.role_code
     *
     * @param roleCode the value for acl_role.role_code
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_role.remark
     *
     * @return the value of acl_role.remark
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_role.remark
     *
     * @param remark the value for acl_role.remark
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_role.is_deleted
     *
     * @return the value of acl_role.is_deleted
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_role.is_deleted
     *
     * @param isDeleted the value for acl_role.is_deleted
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_role.gmt_create
     *
     * @return the value of acl_role.gmt_create
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_role.gmt_create
     *
     * @param gmtCreate the value for acl_role.gmt_create
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_role.gmt_modified
     *
     * @return the value of acl_role.gmt_modified
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_role.gmt_modified
     *
     * @param gmtModified the value for acl_role.gmt_modified
     *
     * @mbggenerated Sun Dec 25 20:30:54 CST 2022
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}